apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: header-example
spec:
  url: oci://ghcr.io/shpwrck/istio-wasm-filter:latest
  pluginConfig:
    cluster: "outbound|8000||httpbin.ext-svc.svc.cluster.local"
    responseMapping:
      Org: X-Org
      Product: X-Product
