apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: header-example
  namespace: int-svc
spec:
  url: oci://ghcr.io/shpwrck/istio-wasm-filter:latest
  pluginConfig:
    cluster: "outbound|80||httpbin.org"
    responseMapping:
      Org: X-Org
      Product: X-Product
